baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'http://tutorial.ddev.site'
primary: true
siteGroup: 836a279c-893f-480b-86ea-e4490791e481 # https://tutorial.ddev.site
sortOrder: 1
