defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  3131252d-4e85-4756-ae37-a4cbe48510af: # http://tutorial.ddev.site
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
