fieldLayouts:
  693e889c-096e-40ab-b0f2-2aa648b24fcb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: Headline
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4d8b8d04-6966-49b9-a13d-d0c45c8dc92e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 88b9be86-f411-46ac-b3cc-bc8f0acc3e8b # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7e7a372c-b9f0-412d-8e90-d176f1ed1861
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 354c7e28-e4ef-4e39-b7f8-2e6364fb677d # Feature Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dda3fc90-0630-43ea-8fc0-a75504fa5735
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9bbab8b0-17b4-4f60-aa82-c2f638e67815 # Post Categories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ca31ee7-9a07-43c3-b04a-c5fffaf97a2b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5fe740bf-73ee-4a1c-bc13-8e1c3f73d16b #  Post Content
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24103259-f02f-4602-9bb1-040148d9e338
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 510db3a6-3f6f-4548-a050-8f96208a475d
        userCondition: null
handle: blog
hasTitleField: true
name: Blog
section: dd04630d-d79e-4415-b5f7-798d09900838 # Blog
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
