columnSuffix: null
contentColumnType: string
fieldGroup: 99e65d72-a8e1-401b-9597-c76ac40d8ee0 # Blog Post Fields
handle: postContent
instructions: null
name: ' Post Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_postcontent}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
